### ISSUE TITLE
Data Viz - charting tools - amCharts

### ISSUE THREAD

**Issue by mg1075** [FrontendMasters/front-end-handbook-2017#12]
https://frontendmasters.gitbooks.io/front-end-handbook-2017/content/tools/charting.html

In the data visualization section, there is a bullet point for amCharts which implies amCharts is only available in a paid version. 

I believe that is incorrrect, and that amCharts is just like Highcharts and others where if you want to use the commercial version, and remove link back to product inside the chart, then you have to buy the commercial version.

- https://www.amcharts.com/
- https://www.amcharts.com/licenses/javascript-charts-free-license/

![image](https://cloud.githubusercontent.com/assets/2031435/22469731/9edbc7ce-e792-11e6-85e9-c88575cf4b5b.png)

![image](https://cloud.githubusercontent.com/assets/2031435/22469639/60004476-e792-11e6-838d-c33f9c81a464.png)

**Comment by codylindley** [comment]
This is a gray area.

"The only limitation of the free version is that a small link to this web site will be displayed in the top left corner of your charts. If you would like to use charts without this link, or you appreciate the software and would like to support its creators, please purchase a commercial license."

But I'll change it to [free to $]

Thanks
