### ISSUE TITLE
Page 9, "Note: Note Edge, IE9 to IE11" - too many "Note"s and it isn't quite clear what is being said.

### ISSUE THREAD

**Issue by scunliffe** [FrontendMasters/front-end-handbook-2017#16]
On page 9, In the most common browser listing the 2nd item for "Internet Explorer has the following suffix: "(Note: Note Edge, IE9 to IE11)" - I'm not quite sure what this should say but it has "note" repeated twice, I'm guessing the second should be "not"?

**Comment by codylindley** [comment]
Thank you. I'll fix and clarify. Appreciate the feedback.
