### ISSUE TITLE
"Front-End Developers to Learn From" should link to "Newsletters, News, and Podcasts"

### ISSUE THREAD

**Issue by taylor-smith** [FrontendMasters/front-end-handbook-2017#19]
Text currently links to the page it is on, https://frontendmasters.gitbooks.io/front-end-handbook-2017/content/learning/learn-from.html. It should link to https://frontendmasters.gitbooks.io/front-end-handbook-2017/content/learning/news-podcasts.html

**Comment by codylindley** [comment]
Pull accepted. Thank you
