### ISSUE TITLE
Request for Simplified Chinese translation

### ISSUE THREAD

**Issue by sqrthree** [FrontendMasters/front-end-handbook-2017#56]
Awesome document 💯. Could we translate this document into simplified Chinese and share with more Chinese developers? We have an organization, and we have translated more than 400 articles. We are looking forward to hearing from you.

About our organization: [github.com/xitu/gold-miner/](https://github.com/xitu/gold-miner/)

**Comment by codylindley** [comment]
Yes. 

From: https://creativecommons.org/licenses/by-nc-nd/3.0/

You are free to:

Share — copy and redistribute the material in any medium or format
The licensor cannot revoke these freedoms as long as you follow the license terms.

**Comment by sqrthree** [comment]
Great! If the work is done, I'll open a PR. Could you add a link to your README.md? :stuck_out_tongue_winking_eye:

**Comment by brucewar** [comment]
@sqrthree Can I join you?

**Comment by sqrthree** [comment]
@brucewar Of course. Please see [github.com/xitu/front-end-handbook-2017/issues/3](https://github.com/xitu/front-end-handbook-2017/issues/3) to get more details.

**Comment by codylindley** [comment]
You should translate the new version, not the 2017 version. The 2018 should be done in the next couple of weeks.

https://github.com/FrontendMasters/front-end-handbook-2018

**Comment by leviding** [comment]
@codylindley Ok, we will translate the new version in the next couple of weeks. You can see the progress [here](https://github.com/xitu/front-end-handbook-2018).

**Comment by codylindley** [comment]
You might hold for a week or two. I still have to finish 2018 version.

**Comment by leviding** [comment]
Ok

**Comment by leviding** [comment]
@codylindley Hi, have you finish  the Front-End Developer Handbook 2018, can we translate it now? If not yet completed, can you inform us once you finish it, then we will start to translate it into Chinese version.

**Comment by codylindley** [comment]
@leviding - Yes, I think you are good to go.

**Comment by leviding** [comment]
@codylindley 👌
