### ISSUE TITLE
Add sanitize.css to CSS Reset section

### ISSUE THREAD

**Issue by lizdizon** [FrontendMasters/front-end-handbook-2017#57]
I noticed the omission of [sanitize.css](https://github.com/jonathantneal/sanitize.css) in the CSS Reset section, which is developed in sync with normalize.css. As a dev who needs to produce pixel-perfect UI, this library saves me from having to manually unset various useragent styles!

**Comment by codylindley** [comment]
Thanks. added. 

https://github.com/FrontendMasters/front-end-handbook-2017/blob/2acd83061eef4d135f53f9ecb6f081276138481b/tools/css.md#css-reset
