### ISSUE TITLE
In section "In 2017 expect..." link "API CMS tools." seems to be broken

### ISSUE THREAD

**Issue by alundiak** [FrontendMasters/front-end-handbook-2017#70]
But I'm not sure what it should have been, by providing google-like link:

"More devs will abandon traditional CMS solutions for static site generators & API CMS tools."

```
https://www.google.com/webhp?sourceid=chrome-instant&rlz=1C5CHFA_enUS712US713&ion=1&espv=2&ie=UTF-8#q=api%20cms
```

@codylindley what was that for? Do you have some valid URL/location/resource?

**Comment by codylindley** [comment]
Good catch, updated: https://github.com/FrontendMasters/front-end-handbook-2017/blob/master/2017.md
