### ISSUE TITLE
Bower is deprecated/dead

### ISSUE THREAD

**Issue by alundiak** [FrontendMasters/front-end-handbook-2017#71]
Resources:
- https://community.plone.org/t/bower-is-now-officially-dead/4246
- https://github.com/bower/bower/issues/2298
- https://github.com/bower/bower/issues/2467
- [Bower now deprecated, suggested to use Yarn or webpack.]( https://www.reddit.com/r/webdev/comments/6c8kpu/bower_now_deprecated_suggested_to_use_yarn_or/)
- https://www.quora.com/Is-Bower-dying
- https://github.com/yarnpkg/yarn/pull/1441
- http://holloway.nz/modern-javascript/bower.png
- https://github.com/yeoman/generator/issues/964

**Comment by codylindley** [comment]
Yup, https://github.com/FrontendMasters/front-end-handbook-2017/blob/e60b508736a8e7c3d2f9a0033652e82b0f8e0f5d/2017.md
