### ISSUE TITLE
Add Chromeheadless to Headless browsers

### ISSUE THREAD

**Issue by ericlam51** [FrontendMasters/front-end-handbook-2017#75]
Chrome 59 now ships with chromeheadless

Resources:
 - https://developers.google.com/web/updates/2017/04/headless-chrome
 - https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

**Comment by codylindley** [comment]
This was updated in a PR.

**Comment by codylindley** [comment]
Should show up soon, under "Headless Browsers": 

https://frontendmasters.com/books/front-end-handbook/2017/tools/browser.html
