### ISSUE TITLE
Outdated newsletters/news sources

### ISSUE THREAD

**Issue by konspekt** [FrontendMasters/front-end-handbook-2017#81]
From what I could see on [Front-End Newsletters, News Sites, & Podcasts](https://frontendmasters.gitbooks.io/front-end-handbook-2017/content/learning/news-podcasts.html), the following sites are no longer maintained (based on their latest updates) and should be removed:

- http://frontenddevweekly.com
- https://frontendfive.codeschool.com
- http://frontendnewsletter.com
- https://webplatformdaily.org/

**Comment by codylindley** [comment]
Updated thanks.
